@startuml
allowmixing
node "Σύστημα Πληρωμών " as Σύστημα_Πληρωμών_ {
}
node "Τρίτες Εφαρμογές" as Τρίτες_Εφαρμογές {
}
node Φορτιστές {
}
node Database {
}
node Backend {
}
node "REST API" as REST_API {
}
node Frontend {
}
node CLI {
}
node "Χρήστης Ηέκτρικου Οχήματος" as Χρήστης_Ηέκτρικου_Οχήματος {
}
CLI ..> REST_API
REST_API ..> CLI
Χρήστης_Ηέκτρικου_Οχήματος ..> Frontend
Frontend ..> Χρήστης_Ηέκτρικου_Οχήματος
Frontend ..> REST_API
Backend ..> REST_API
REST_API ..> Backend
Backend ..> Database
Database ..> Backend
Backend ..> Σύστημα_Πληρωμών_
Σύστημα_Πληρωμών_ ..> Backend
Τρίτες_Εφαρμογές ..> Backend
Φορτιστές ..> Backend
@enduml